theme: jekyll-theme-leap-day  # Example theme, you can change this to your preferred theme
markdown: kramdown

# Add the MathJax script to the head section
head:
  - "<script type='text/javascript' async src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML'></script>"
  - "<script type='text/javascript'      MathJax.Hub.Queue(['Typeset', MathJax.Hub]);  '></script>"
  
include:
  - _includes/mathjax.html
